const siteConfig = {
  name: "Herceg Novi Car Rental",
  tagline: "Drive the Montenegrin Riviera",
  domain: "carrentalhercegnovi.com",
  phone: "",
  email: "info@carrentalhercegnovi.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Herceg Novi Car Rental — Gateway to the Bay",
    subheadline: "Pick up your rental car in Herceg Novi — just 35km from Tivat Airport and the gateway from Dubrovnik into Montenegro.",
    image: "/img/hero-budva.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Airport Pickup", description: "Tivat Airport is 35 km from Herceg Novi along the bay road. Your agent meets you at arrivals — one scenic drive through the Bay of Kotor and you're at your hotel." },
    { icon: "shield-check", title: "Full Insurance", description: "CDW and theft cover included as standard. Upgrade to zero excess for total peace of mind on narrow old town lanes and the Croatian motorway to Dubrovnik." },
    { icon: "clock", title: "24/7 Support", description: "Flat tyre on the Lustica road? Lost your keys at Igalo spa? Call us any hour — we know every street and car park around the bay." },
    { icon: "ban", title: "No Hidden Fees", description: "One number at booking. That same number at pickup. VAT, mileage, and fuel policy are all baked in — nothing added at the counter." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Plans change — especially when you're juggling bay towns and border crossings. Cancel free up to 24 hours before your pickup and get every cent refunded." },
    { icon: "globe", title: "Cross-Border to Croatia", description: "Dubrovnik is just 30 km away via Debeli Brijeg border crossing. Green card sorted at booking — drive to Croatia and back the same day." },
  ],

  testimonials: [
    { name: "Maria & Stefan", location: "Vienna, Austria", text: "We spent a week based in Igalo for the spa treatments and used the car every day. Drove to Savina Monastery one morning, then down to Kotor in the afternoon. The bay views from the road above Herceg Novi are unforgettable. Pickup at Tivat was seamless.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "James & Sophie", location: "London, UK", text: "We flew into Dubrovnik and drove to Herceg Novi in under an hour — the border crossing was quick and painless. Spent two days exploring Forte Mare and the old town, then drove around the whole bay. Having a car made the Dubrovnik day trip so easy. Highly recommend.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Luka & Ana", location: "Zagreb, Croatia", text: "Rented for four nights to explore the bay properly. The drive from Herceg Novi to Perast along the waterfront was the highlight of our trip. We stopped at Risan for the mosaics, visited Savina Monastery twice, and watched the sunset from the fortress. The car was clean and the agent very helpful.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need to rent?", a: "You'll need a full driving licence with Latin-script details, your passport, and a physical credit card issued in the main driver's name. If your licence is from a country that uses a non-Latin script, bring an International Driving Permit as well. Photocopies and digital-only licences are not accepted at pickup." },
    { q: "Can I drive to Croatia or Albania?", a: "Yes. Cross-border travel is permitted to Croatia, Bosnia, Albania, Kosovo, and Serbia. Dubrovnik is the most popular run from Herceg Novi — just 30 km via the Debeli Brijeg border crossing. Flag the countries at booking and the Green Card is prepared for you." },
    { q: "Is there a minimum age to rent?", a: "Age and licence experience requirements vary by vehicle class and are listed clearly in each car's details when you search. Younger drivers may see a small daily supplement depending on the model." },
    { q: "What's actually included in the price?", a: "Third-party liability insurance and CDW come standard on most cars. VAT, a roadside safety kit, and a transparent fuel policy are included too. Mileage terms differ per vehicle — check the car listing. Zero-excess cover and extras like child seats can be added at booking." },
    { q: "Where can I pick up the car?", a: "Pickup is available at Herceg Novi centre, Igalo, and Tivat Airport (35 km). Your agent meets you at the agreed location — no shuttle buses, no queues. Just select your preferred spot when you book." },
    { q: "Can I return the car somewhere different?", a: "One-way rentals are available across 28+ towns and cities in Montenegro. Pick up in Herceg Novi, drop off at Tivat Airport, or vice versa — just select different locations when you book." },
    { q: "What is the cancellation policy?", a: "Standard vehicles: free cancellation up to 7 days before pickup. Luxury cars and convertibles: free cancellation up to 30 days in advance. A 6% processing fee applies on all cancellations regardless of timing." },
    { q: "Do I need to pay a deposit?", a: "It depends on the vehicle. Deposits typically fall between €100 and €500. Some cars require no deposit at all. Where one applies, it sits on the main driver's physical credit card and is released when the car is returned undamaged." },
    { q: "What if I go over my mileage allowance?", a: "Vehicles with a set mileage cap charge a per-kilometre fee for any distance above the limit. The exact overage rate is shown in the car details before you confirm — no surprises." },
    { q: "Is the price I see the price I pay?", a: "Yes. All taxes and standard fees are folded into the booking price. There is no fuel surcharge, airport levy, or desk fee added when you collect the car." },
    { q: "How much do I pay to confirm the booking?", a: "A deposit of roughly 15% to 20% of the total secures the reservation. The rest is settled directly with the rental agent when you pick up the car in Herceg Novi or at Tivat." },
    { q: "Can I rent without a credit card?", a: "Certain vehicles in the fleet can be rented with a debit card or without a card altogether. These are labelled in the search results so you can filter accordingly." },
  ],

  locations: [
    { name: "Herceg Novi Centre", tag: "Most Popular" },
    { name: "Igalo", tag: "Spa Town" },
    { name: "Tivat Airport", tag: "35 km" },
    { name: "Savina Monastery", tag: "" },
    { name: "Kotor", tag: "" },
    { name: "Dubrovnik Airport", tag: "" },
  ],

  destinations: [
    {
      name: "Igalo",
      slug: "igalo",
      tag: "Spa Town",
      desc: "Famous for its therapeutic mud baths and spa hotels, just west of Herceg Novi.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "UNESCO Site",
      desc: "Medieval walled city on the bay, 45 km from Herceg Novi.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "35 km Away",
      desc: "The nearest airport. Your agent meets you at arrivals.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Fly into Dubrovnik, drive to Herceg Novi in under an hour.",
      image: "/img/dubrovnik-nearby.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "Riviera Capital",
      desc: "Beach capital of Montenegro, 55 km down the coast.",
      image: "/img/budva-old-town.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "Hidden Gem",
      desc: "Baroque village on the Bay of Kotor with island churches.",
      image: "/img/perast-village.webp",
    },
    {
      name: "Risan",
      slug: "risan",
      tag: "Roman Mosaics",
      desc: "Ancient town with Roman mosaics on the inner bay.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Lustica Peninsula",
      slug: "lustica-peninsula",
      tag: "Hidden Beaches",
      desc: "Wild beaches and olive groves on the peninsula across the bay.",
      image: "/img/porto-montenegro.webp",
    },
  ],
};

export default siteConfig;
