const siteConfig = {
  name: "Car Rental Herceg Novi",
  heroImage: "/img/hero-green-minicooper.jpg",
  tagline: "The western edge of the Adriatic, at the Croatian border",
  domain: "carrentalhercegnovi.com",
  phone: "",
  email: "info@carrentalhercegnovi.com",
  address: "Trg Mičela Komnena, Herceg Novi, 85340",

  hero: {
    headline: "Rent a Car in Herceg Novi",
    subheadline: "The entrance to the Bay of Kotor, Dubrovnik 40 minutes one way, Kotor Old Town 30 minutes the other. Orjen Mountain behind. Mamula Island offshore.",
    image: "/img/hero-green-minicooper.jpg",
  },

  cars: [
    {
      id: 1,
      slug: "renault-clio",
      typeGroup: "economy",
      name: "Renault Clio",
      category: "Economy",
      tagline: "The low-maintenance coast-runner for a fortnight-long Herceg Novi base",
      lede: "Light on fuel, cheap to park at the pickup location, and comfortable on the motorway push to Podgorica or Žabljak.",
      price: 28,
      image: "/img/fleet/renault-clio.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Bluetooth Audio","USB Charging","Central Locking","Touchscreen Display"],
      details: {
        engine: "1.0 TCe 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.3 L/100 km",
        bootSize: "391 L",
        length: "4,050 mm",
        topSpeed: "188 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["Couples on a two-week stay", "Day-trippers to Cetinje and Njeguši", "Shoppers at Risan Roman mosaics"],
      suitability: "A pair settling in Herceg Novi for ten to fourteen days, with regular day-trips out to Cetinje, Risan and the Lake Skadar shore, simple to park, forgiving on petrol.",
      regional: "Handles the Herceg Novi–Cetinje climb in third gear without drama, threads the narrow waterfront through outlying villages, and the 5.3 L/100 km petrol keeps the fuel bill predictable over a multi-week hire.",
    },
    {
      id: 2,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Diesel mid-size for the Herceg Novi → Dubrovnik and Herceg Novi → Durmitor runs",
      lede: "Long-legged BlueHDi + auto box built for the 3-hour push up to Žabljak or the cross-border drive to Trebinje and Mostar.",
      price: 38,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Automatic Transmission","Adaptive Cruise","Dual-Zone Climate","Large Boot"],
      details: {
        engine: "1.5 BlueHDi 4-cyl diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,309 L seats folded)",
        length: "4,367 mm",
        topSpeed: "206 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd auto",
      },
      popular: true,
      bestFor: ["Cross-border road-trippers","Durmitor weekenders","Four adults with full luggage"],
      suitability: "The mid-size diesel picks for anyone pairing a Herceg Novi base with multi-day drives inland, auto gearbox and cruise control earn their keep on the Podgorica motorway.",
      regional: "Cruises the Smokovac–Mateševo motorway section effortlessly, swallows a week of hiking kit bound for Žabljak, and covers the Herceg Novi → Dubrovnik via Debeli Brijeg run on half a tank.",
    },
    {
      id: 3,
      slug: "renault-megane",
      typeGroup: "midsize",
      name: "Renault Megane",
      category: "Mid-Size",
      tagline: "Biggest-boot French mid-size, built for long-stay loads and lake trips",
      lede: "434-litre boot, quiet diesel cruising, sofa-soft damping, the mid-size wagon pick for a month in the bay with regular excursions out.",
      price: 36,
      image: "/img/fleet/renault-megane.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Large Boot","Bluetooth Audio","Cruise Control","Parking Sensors"],
      details: {
        engine: "1.5 Blue dCi 4-cyl diesel",
        power: "115 hp",
        consumption: "4.3 L/100 km",
        bootSize: "434 L",
        length: "4,360 mm",
        topSpeed: "195 km/h",
        acceleration: "11.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Long-stay renters","Skadar Lake day-trippers","Families visiting monasteries"],
      suitability: "Renters who want more than a hatchback's packing space without the length of a full estate, ideal for Skadar Lake fishing kit, Cetinje monastery day-bags and a cool-box for the drive home.",
      regional: "The long-travel suspension shrugs off the patchy bitumen on the old Herceg Novi–Budva road, the dCi diesel sips on the Sozina tunnel run, and the generous boot takes two weeks of family kit plus the laundry bag you pick up in Prčanj.",
    },
    {
      id: 4,
      slug: "peugeot-208",
      typeGroup: "economy",
      name: "Peugeot 208",
      category: "Economy",
      tagline: "Small-footprint French hatch, the cheapest way onto the Herceg Novi waterfront",
      lede: "Lightest, cheapest runaround in the fleet. i-Cockpit gauges, PureTech 1.2 petrol, and a small enough footprint to slip into the bastion car-parks at the Sea Gate.",
      price: 22,
      image: "/img/fleet/peugeot-208.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["i-Cockpit Digital Dash","Bluetooth Audio","Cruise Control","USB Charging"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "75 hp",
        consumption: "4.7 L/100 km",
        bootSize: "311 L",
        length: "4,055 mm",
        topSpeed: "173 km/h",
        acceleration: "12.0s (0–100 km/h)",
        driveType: "Front-wheel drive, 5-spd manual",
      },
      popular: false,
      bestFor: ["Budget solo travellers","Weekend breaks from Dubrovnik","Short Herceg Novi stays"],
      suitability: "The cheapest economy slot in the fleet, for a short 3- to 5-night stay with daily coffee runs to the Old Town and afternoon drives out to Žanjic and Mirište.",
      regional: "The 4.05 m length parks in the same bays a Clio takes, the 311-litre boot swallows two carry-ons plus a cool-box, and the 4.7 L/100 km petrol keeps a week of Kotor-Perast pottering under €25 of fuel.",
    },
    {
      id: 5,
      slug: "hyundai-i20",
      typeGroup: "economy",
      name: "Hyundai i20",
      category: "Economy",
      tagline: "Quiet Korean hatch, the refined choice in the small-car class",
      lede: "Plusher cabin than the French rivals, refined 1.2 MPi petrol, lane-keep and AEB as standard. The small-car pick when you want a quieter drive than a Clio or Fiesta.",
      price: 24,
      image: "/img/fleet/hyundai-i20.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Lane Keep Assist","Autonomous Braking","Apple CarPlay","Reversing Camera"],
      details: {
        engine: "1.2 MPi 4-cyl petrol",
        power: "84 hp",
        consumption: "5.1 L/100 km",
        bootSize: "262 L",
        length: "4,040 mm",
        topSpeed: "170 km/h",
        acceleration: "13.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 5-spd manual",
      },
      popular: false,
      bestFor: ["Older couples on relaxed stays","First-time Balkan drivers","Renters nervous about Adriatic traffic"],
      suitability: "A soft, unflustered small hatch for renters who want modern safety kit without paying mid-size prices. Ideal week-long Herceg Novi base with trips to Perast, Tivat, Risan.",
      regional: "The 4-cylinder engine is noticeably smoother than the 3-pot alternatives on the long motorway push to Podgorica, and lane-keep assist takes the edge off the tight cambered sections through Morinj and Kostanjica.",
    },
    {
      id: 6,
      slug: "toyota-yaris",
      typeGroup: "economy",
      name: "Toyota Yaris",
      category: "Economy",
      tagline: "Reliable Toyota hatch, the 'never breaks down' option for longer road trips",
      lede: "The small-car pick if reliability matters more than badge cachet. 1.5 four-cylinder with Toyota's legendary service intervals, zero worry even on a three-week rental.",
      price: 26,
      image: "/img/fleet/toyota-yaris.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Toyota Safety Sense","Automatic Headlights","Bluetooth","Adaptive Cruise"],
      details: {
        engine: "1.5 VVT-iE 3-cyl petrol",
        power: "125 hp",
        consumption: "4.8 L/100 km",
        bootSize: "286 L",
        length: "3,940 mm",
        topSpeed: "175 km/h",
        acceleration: "9.7s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Long-stay renters (2+ weeks)","Road-trippers looping the whole country","Nervous first-time renters"],
      suitability: "For renters who pick the car on past reliability rather than styling, the Yaris is the most forgiving small hatch on the Herceg Novi → Durmitor → Podgorica → back loop.",
      regional: "125 hp has genuine pace for the Lovćen climb, the 3.94 m length is the shortest in the economy lineup aside from the Ignis, and Toyota Safety Sense manages the sudden lane-merges on the Sozina tunnel approach.",
    },
    {
      id: 7,
      slug: "ford-fiesta",
      typeGroup: "economy",
      name: "Ford Fiesta",
      category: "Economy",
      tagline: "Ford's best-handling small car, the pick for the Herceg Novi → Lovćen hairpins",
      lede: "The enthusiast's small hatch. 1.0 EcoBoost 3-cyl makes real pace, and Ford's chassis tuning turns the Lovćen switchbacks into a highlight rather than an endurance test.",
      price: 25,
      image: "/img/fleet/ford-fiesta.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["EcoBoost Turbo","Hill-Start Assist","Bluetooth","USB-C Charging"],
      details: {
        engine: "1.0 EcoBoost 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.0 L/100 km",
        bootSize: "292 L",
        length: "4,068 mm",
        topSpeed: "184 km/h",
        acceleration: "10.9s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Enthusiast drivers","Coastal road explorers","Renters doing the Lovćen switchbacks"],
      suitability: "A small car that actually rewards driving. For renters whose itinerary includes the Lovćen 25-bends, the cross-bay coast road through Kostanjica, or the winding back route via Grahovo.",
      regional: "The 100 hp turbo hauls cleanly out of the Herceg Novi bastion tunnels, six-speed gearing keeps the engine in its sweet spot on the E65 grade, and the precise steering is the real reason to pick a Fiesta over a Clio for the mountain drives.",
    },
    {
      id: 8,
      slug: "suzuki-ignis",
      typeGroup: "suv",
      name: "Suzuki Ignis",
      category: "Mini Crossover",
      tagline: "Pocket crossover, raised ride for the gravel spur to Žanjic and Mirište",
      lede: "Tiny footprint plus genuine ride height. The pick for coves reached by dirt tracks, Žanjic, Mirište, the back road to Rose fishing village, without jumping to a full SUV.",
      price: 24,
      image: "/img/fleet/suzuki-ignis.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 1,
      ac: true,
      features: ["Raised Ride Height","Compact Dimensions","Bluetooth","Rear Parking Sensors"],
      details: {
        engine: "1.2 Dualjet 4-cyl petrol",
        power: "83 hp",
        consumption: "4.9 L/100 km",
        bootSize: "204 L",
        length: "3,700 mm",
        topSpeed: "165 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Luštica peninsula explorers","Off-the-beaten-track couples","Photographers chasing gravel-road coves"],
      suitability: "The fleet's quirky pick: higher ride height than a hatchback, smaller footprint than any SUV. Designed for Luštica's unpaved spurs to secluded beaches.",
      regional: "180 mm ground clearance clears the deep ruts on the last 2 km of dirt track down to Žanjic beach, the 3.7 m length parks at the Sea Gate where a mid-size can't, and the four-cylinder engine is noticeably quieter than the 3-pot rivals.",
    },
    {
      id: 9,
      slug: "citroen-c4",
      typeGroup: "midsize",
      name: "Citroen C4",
      category: "Mid-Size",
      tagline: "French mid-size with Advanced Comfort suspension, the softest ride in the fleet",
      lede: "380-litre boot, PureTech 130, and Citroën's Advanced Comfort hydraulic bump stops that iron out the patched bitumen on the old coast road. The gentlest mid-size for long drives.",
      price: 32,
      image: "/img/fleet/citroen-c4.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Advanced Comfort Suspension","10-inch Touchscreen","Adaptive Cruise","Wireless CarPlay"],
      details: {
        engine: "1.2 PureTech turbo petrol",
        power: "130 hp",
        consumption: "5.2 L/100 km",
        bootSize: "380 L",
        length: "4,360 mm",
        topSpeed: "208 km/h",
        acceleration: "9.9s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Comfort-first couples","Renters with back issues","Four adults on a slow tour"],
      suitability: "The mid-size pick for renters who prioritise comfort over performance, perfect for a week mixing the Herceg Novi base with day-trips out to Budva, Stari Bar, or the north.",
      regional: "Progressive hydraulic bump stops smooth the broken stretch between Risan and Perast, the 380-litre boot fits four cases plus beach gear, and the 130 hp is plenty for overtaking slow tourist traffic on the E80 to Budva.",
    },
    {
      id: 10,
      slug: "citroen-c3",
      typeGroup: "economy",
      name: "Citroen C3",
      category: "Economy",
      tagline: "Softest small hatch for the broken Herceg Novi–Risan stretch and back-road detours",
      lede: "Advanced Comfort dampers iron out the patched tarmac on the old bay road, the gentlest small car to park at the Herceg Novi bastions overnight.",
      price: 27,
      image: "/img/fleet/citroen-c3.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Advanced Comfort Seats","Bluetooth Audio","USB Charging","Lane Departure Warning"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "83 hp",
        consumption: "5.5 L/100 km",
        bootSize: "300 L",
        length: "3,996 mm",
        topSpeed: "175 km/h",
        acceleration: "13.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Slow-touring couples","Back-road explorers","Renters prone to motion sickness"],
      suitability: "The comfort-first pick for a week in Herceg Novi with daily slow-paced detours, Risan's Roman mosaics, the Gornja Lastva hamlet above Tivat, the loop back through nearby villages.",
      regional: "The progressive hydraulic bump stops make the potholed stretch from Risan to Perast feel a size-class quieter, the low-stress 83 hp motor suits the 50 km/h bay-road limits, and the 4-metre length slots into any Old Town bastion bay.",
    },
    {
      id: 11,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised-ride crossover for the gravel approach to Njeguši and Lovćen",
      lede: "A slightly higher-riding alternative to a hatchback, takes the rutted spur roads around Njeguši and the Lovćen back approaches without scraping.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height","Apple CarPlay","Reversing Camera","Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Weekend trippers to Njeguši","Durmitor day-trippers","Photographers chasing ridge viewpoints"],
      suitability: "Renters who want crossover sight-lines and a bit of ground clearance for the side-roads around Herceg Novi's upper bay and the Lovćen approach, without paying full-SUV money.",
      regional: "Higher seating position means easier viewing over region parapet walls, the 182 mm ride height clears the stone ruts on the old Njeguši ham-smoker lane, and the 352-litre boot handles a family's Durmitor hiking gear without folding seats.",
    },
    {
      id: 12,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "DSG diesel all-rounder, calm cruising for the E80 and multi-day loops",
      lede: "The rational default for a renter mixing a Herceg Novi base with long inland drives, refined, quick enough, and economical on the motorway.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples mixing coast and canyon", "Business travellers on week-long hires", "Drivers planning the BiH or Croatia border run"],
      suitability: "The default mid-size for renters who want one car that will do the Herceg Novi Old Town perimeter on day one and the Smokovac-Mateševo motorway on day four without complaint.",
      regional: "DSG picks the right ratio on the Herceg Novi–Lovćen hairpins without any thinking, the 2.0 TDI holds 130 km/h on the motorway section up to Podgorica at 4.3 L/100 km, and the cabin quiet makes the 3-hour push to Žabljak genuinely relaxing.",
    },
    {
      id: 13,
      slug: "fiat-500",
      typeGroup: "economy",
      name: "Fiat 500",
      category: "City",
      tagline: "Postage-stamp city car for a short Herceg Novi stay, slots between delivery vans",
      lede: "Tiny footprint, sunroof, hybrid-assisted 1.0, the pick for a two- or three-night Herceg Novi anchor when multi-day drives aren't on the schedule.",
      price: 20,
      image: "/img/fleet/fiat-500.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      details: {
        engine: "1.0 L mild-hybrid petrol",
        power: "70 hp",
        consumption: "5.4 L/100 km",
        bootSize: "185 L",
        length: "3,571 mm",
        topSpeed: "167 km/h",
        acceleration: "13.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Short city-base stays", "Solo visitors on a shoestring", "Photographers doing short hops"],
      suitability: "Two or three nights in Herceg Novi with short afternoon hops to Perast and Prčanj, the 500 parks where mid-size cars wave and drive past.",
      regional: "The 3.57 m length is the deciding factor: it fits the stepped terrace parking on the nearby villages waterfront and the shoulder-wide gap outside the Sea Gate that a Clio can't. Underpowered for the Lovćen climb, so pair with cable-car transfers or keep within bay limits.",
    },
  ],

  features: [
    { icon: "map-pin", title: "Herceg Novi Pickup", description: "Meet us on the Herceg Novi waterfront, at your Igalo hotel, or at Tivat Airport 40 minutes away. Dubrovnik Airport pickup also supported for arrivals from Croatia." },
    { icon: "shield-check", title: "Border-Ready Insurance", description: "CDW, theft and third-party liability on every rental, plus Green Card cover for the Croatia crossing at Debeli Brijeg. Zero-excess upgrade recommended for Orjen mountain drives." },
    { icon: "clock", title: "24/7 Local Support", description: "Queue stuck at Debeli Brijeg, puncture on the Orjen road, last boat missed from Mamula, we answer any hour." },
    { icon: "ban", title: "No Hidden Charges", description: "The price you book is the price you pay. No summer premium, no fuel-tier tricks, no surprise airport fees." },
    { icon: "refresh-cw", title: "Flexible Cancellation", description: "Cancel free of charge up to seven days before pickup on most vehicles." },
    { icon: "globe", title: "Cross to Croatia", description: "Dubrovnik is 40 minutes away over the Debeli Brijeg border, Green Card included when you tell us at booking." },
  ],

  testimonials: [
    { name: "Pavel & Tereza", location: "Prague, Czech Republic", text: "Ferry from Italy to Igoumenitsa, drove north through Albania, arrived Herceg Novi in the evening. Hired a Skoda here for a week. Day trip to Dubrovnik, a boat to Mamula, Orjen hike on day four. The border queue was as bad as everyone warned but otherwise flawless.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Helen Whitaker", location: "Bath, England", text: "Flew Dubrovnik, took a taxi to the border, picked up the car in Herceg Novi. Saved a fortune on cross-border rental fees. Based at Igalo for the mud spa, did short coastal drives most afternoons. Car was spotless, staff helpful.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "The Becker Family", location: "Munich, Germany", text: "Four of us in a Toyota Corolla hybrid. Best fuel economy we've had on any Balkan trip. Stayed in Herceg Novi for four nights, drove to Kotor and Budva on day trips. Boat day to the Blue Cave was the highlight for the kids.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "Which airport is closest?", a: "Tivat Airport (TIV) is 40 minutes away and the main option. Dubrovnik Airport (DBV) in Croatia is 40 minutes in the other direction, plus border crossing time, sometimes faster overall from northern Europe." },
    { q: "Can I pick up in Croatia and drop off in Montenegro?", a: "Most operators charge substantial one-way fees for cross-border drops. Renting in Herceg Novi and taxiing across the border is often cheaper." },
    { q: "How long is the Dubrovnik border queue?", a: "Debeli Brijeg takes 15-60 minutes typically. Summer weekends can stretch to two hours. Avoid 10:00-13:00 on Saturdays." },
    { q: "Minimum age?", a: "21 with two years of driving experience. 21-24 year olds pay a young-driver surcharge." },
    { q: "Is a credit card required?", a: "Most vehicles hold €100-€350 on a credit card. A few economy options accept debit with a larger deposit, filter for 'no credit card required' at booking." },
    { q: "Cross-border paperwork?", a: "Croatia, Bosnia, Serbia, Albania and Kosovo all supported. Green Card insurance included when you tell us your plans at booking." },
    { q: "Winter driving?", a: "Coast is mild year-round. Orjen Mountain and the inland passes need winter tyres November-April, included on mountain-class vehicles." },
    { q: "Parking in Herceg Novi?", a: "The Old Town is pedestrianised (stairs, not streets). Park at the waterfront lots (€1-2/hr) and walk up." },
    
    { q: "Mileage limit?", a: "Most rentals are unlimited. Budget economy vehicles sometimes cap at 200 km/day, visible at booking." },
    { q: "Late-night airport arrivals?", a: "Every flight met at Tivat, no surcharge. Dubrovnik pickups require 24 hours notice." },
    { q: "What if my ferry is delayed?", a: "We track ferries from Bari, Ancona and Dubrovnik port and adjust pickup times. No surcharge for delays." },
  ],

  locations: [
    { name: "Herceg Novi", tag: "Most Popular" },
    { name: "Igalo", tag: "Spa Resort" },
    { name: "Tivat Airport", tag: "Airport Pickup" },
    { name: "Dubrovnik Airport", tag: "Cross-Border" },
    { name: "Bijela", tag: "" },
    { name: "Meljine", tag: "" },
  ],

  destinations: [
    { name: "Kamenari–Lepetane Ferry", slug: "blog/kamenari-lepetane-ferry", tag: "~5 min crossing", desc: "The roll-on ferry shortcut across the narrowest point of the Bay of Kotor.", image: "/img/blog-kamenari-lepetane-ferry.webp" },
    { name: "Rose Village", slug: "blog/rose-village-lustica", tag: "Luštica peninsula", desc: "A 14th-century fishing hamlet with Austrian battery ruins above.", image: "/img/blog-rose-village-lustica.webp" },
    { name: "Ledenice Loop", slug: "blog/ledenice-viewpoint-loop", tag: "~700 m altitude", desc: "The switchback road above Herceg Novi and the best bay panorama on the west Boka.", image: "/img/blog-ledenice-viewpoint-loop.webp" },
    { name: "Risan Roman Mosaics", slug: "blog/risan-roman-mosaics-drive", tag: "Inner bay", desc: "An ancient Illyrian capital and a Roman villa floor mosaic of Hypnos.", image: "/img/blog-risan-roman-mosaics-drive.webp" },
    { name: "Portonovi Marina", slug: "blog/portonovi-marina-podi", tag: "5 km east", desc: "The former Yugoslav naval base at Kumbor, now a superyacht marina.", image: "/img/blog-portonovi-marina-podi.webp" },
    { name: "Bijela Shipyards", slug: "blog/bijela-shipyards-heritage", tag: "Since 1927", desc: "The working dry-dock town on the outer bay magistrala.", image: "/img/blog-bijela-shipyards-heritage.webp" },
    { name: "Đenovići Promenade", slug: "blog/djenovici-west-bay-promenade", tag: "Austro-Hungarian villas", desc: "A low-rise coastal strip and walking promenade east of Herceg Novi.", image: "/img/blog-djenovici-west-bay-promenade.webp" },
    { name: "Airport Choice", slug: "blog/tivat-vs-dubrovnik-airport-choice", tag: "Tivat vs Dubrovnik", desc: "Two airports, roughly equal drive time, a decision guide.", image: "/img/blog-tivat-vs-dubrovnik-airport-choice.webp" },
  ],
};

export default siteConfig;
